# Build and test CPAN module: GoogleTranslateLanguages

name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: |
        sudo apt update
        sudo apt -y install build-essential tree
        sudo cpan install Module::Build

    - name: InstallDataTableText
      run: |
        sudo cpan install Data::Table::Text

    - name: InstallISO639
      run: |
        sudo cpan install ISO::639



    - name: Test
      run: |
        tree
        perl Build.PL
        perl Build test
